describe('delete user', () => {
    it('success delete user', () => {
      cy.visit('https://opensource-demo.orangehrmlive.com/')
      cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Admin')
      cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
      cy.get('.oxd-button').click()
      cy.get('.oxd-brand-banner > img').should('be.visible')
      cy.get(':nth-child(1) > .oxd-main-menu-item > .oxd-text').click()
      cy.get(':nth-child(3) > .oxd-topbar-body-nav-tab-item').click()
      cy.get('.oxd-dropdown-menu > :nth-child(2)').click()
      cy.get(':nth-child(10) > .oxd-table-row > :nth-child(7) > .oxd-table-cell-actions > :nth-child(1) > .oxd-icon').click()
      cy.get('.oxd-button--label-danger').click()
    })
    it('delete user failed', () => {
        cy.visit('https://opensource-demo.orangehrmlive.com/')
        cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Admin')
        cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
        cy.get('.oxd-button').click()
        cy.get('.oxd-brand-banner > img').should('be.visible')
        cy.get(':nth-child(1) > .oxd-main-menu-item > .oxd-text').click()
        cy.get(':nth-child(3) > .oxd-topbar-body-nav-tab-item').click()
        cy.get('.oxd-dropdown-menu > :nth-child(2)').click()
        cy.get(':nth-child(8) > .oxd-table-row > :nth-child(7) > .oxd-table-cell-actions > :nth-child(1) > .oxd-icon').click()
        cy.get('.oxd-button--text').click()
    })

})