import baseAddEmployee from "../../support/PageObject/employee/baseAddEmployee.cy.js"

describe('Edit Locations', () => {

    it('success edit locations', () => {
      const BaseAddEmployee = new baseAddEmployee()
    // login
      cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Admin')
      cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
      cy.get('.oxd-button').click()
      cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('contain.text', 'Dashboard')

      cy.get(':nth-child(1) > .oxd-main-menu-item').click()
      cy.get(':nth-child(3) > .oxd-topbar-body-nav-tab-item').click()
      cy.get('.oxd-dropdown-menu > :nth-child(2)').click()
      cy.get(':nth-child(2) > .oxd-table-row > :nth-child(7) > .oxd-table-cell-actions > :nth-child(2)').click()
      cy.get(':nth-child(1) > .oxd-grid-2 > .oxd-grid-item > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('Amodalin Capa')
      cy.get(':nth-child(2) > .oxd-grid-2 > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('Majalengka')
      cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('+1234567')
      cy.get(':nth-child(5) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('088654765234')
      cy.get(':nth-child(7) > .oxd-input-group > :nth-child(2) > .oxd-textarea').clear().type('Jl. Pemuda Negara no 23')
      cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('Jawa Timur')
      cy.get('.oxd-select-text').click()
      cy.get(':nth-child(101)').click()
      cy.get(':nth-child(6) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('111-0123')
      cy.get(':nth-child(8) > .oxd-input-group > :nth-child(2) > .oxd-textarea').clear().type('Perubahan diperlukan')
      cy.get('.oxd-button--secondary').click()
    }) 
    
    it('failed edit locations', () => {             //Gagal karena empty name (required)
        const BaseAddEmployee = new baseAddEmployee()
      // login
        cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
        cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin')
        cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
        cy.get('.oxd-button').click()
        cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('contain.text', 'Dashboard')
  
        cy.get(':nth-child(1) > .oxd-main-menu-item').click()
        cy.get(':nth-child(3) > .oxd-topbar-body-nav-tab-item').click()
        cy.get('.oxd-dropdown-menu > :nth-child(2)').click()
        cy.get(':nth-child(2) > .oxd-table-row > :nth-child(7) > .oxd-table-cell-actions > :nth-child(2)').click()
        cy.get(':nth-child(1) > .oxd-grid-2 > .oxd-grid-item > .oxd-input-group > :nth-child(2) > .oxd-input').clear()
        cy.get(':nth-child(2) > .oxd-grid-2 > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('Majalengka')
        cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('+1234567')
        cy.get(':nth-child(5) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('088654765234')
        cy.get(':nth-child(7) > .oxd-input-group > :nth-child(2) > .oxd-textarea').clear().type('Jl. Pemuda Negara no 23')
        cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('Jawa Timur')
        cy.get('.oxd-select-text').click()
        cy.get(':nth-child(101)').click()
        cy.get(':nth-child(6) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('111-0123')
        cy.get(':nth-child(8) > .oxd-input-group > :nth-child(2) > .oxd-textarea').clear().type('Perubahan diperlukan')
        cy.get('.oxd-button--secondary').click()
      })

      it('failed edit locations', () => {             //Gagal karena empty country (required)
        const BaseAddEmployee = new baseAddEmployee()
      // login
        cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
        cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin')
        cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
        cy.get('.oxd-button').click()
        cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('contain.text', 'Dashboard')
  
        cy.get(':nth-child(1) > .oxd-main-menu-item').click()
        cy.get('.oxd-topbar-body-nav > ul > :nth-child(3)').click()
        cy.get('.oxd-dropdown-menu > :nth-child(2)').click()
        cy.get(':nth-child(2) > .oxd-table-row > :nth-child(7) > .oxd-table-cell-actions > :nth-child(2)').click()
        cy.get(':nth-child(1) > .oxd-grid-2 > .oxd-grid-item > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('Amodalin Capa')
        cy.get(':nth-child(2) > .oxd-grid-2 > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('Majalengka')
        cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('+1234567')
        cy.get(':nth-child(5) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('088654765234')
        cy.get(':nth-child(7) > .oxd-input-group > :nth-child(2) > .oxd-textarea').clear().type('Jl. Pemuda Negara no 23')
        cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('Jawa Timur')
        cy.get('.oxd-select-text').click()
        cy.get('.oxd-select-dropdown > :nth-child(1)').click()
        cy.get(':nth-child(6) > .oxd-input-group > :nth-child(2) > .oxd-input').clear().type('111-0123')
        cy.get(':nth-child(8) > .oxd-input-group > :nth-child(2) > .oxd-textarea').clear().type('Perubahan diperlukan')
        cy.get('.oxd-button--secondary').click()
      })
  })
  
  