describe('Search Organization', () => {
    it('success search Organization', () => {
      cy.visit('https://opensource-demo.orangehrmlive.com/')
      cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Admin')
      cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
      cy.get('.oxd-button').click()
      cy.get('.oxd-brand-banner > img').should('be.visible')
      cy.get(':nth-child(1) > .oxd-main-menu-item > .oxd-text').click()
      cy.get(':nth-child(3) > .oxd-topbar-body-nav-tab-item').click()
      cy.get('.oxd-dropdown-menu > :nth-child(2)').click()
      cy.get(':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Texas R&D')
      cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Texas')
      cy.get('.oxd-select-text').click({force: true})
      cy.get(':nth-child(227)').click({force: true})
      cy.get('.oxd-form-actions > .oxd-button--secondary').click({force: true})
    })
    it('success search Organization empty city', () => {
      cy.visit('https://opensource-demo.orangehrmlive.com/')
      cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Admin')
      cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
      cy.get('.oxd-button').click()
      cy.get('.oxd-brand-banner > img').should('be.visible')
      cy.get(':nth-child(1) > .oxd-main-menu-item > .oxd-text').click()
      cy.get(':nth-child(3) > .oxd-topbar-body-nav-tab-item').click()
      cy.get('.oxd-dropdown-menu > :nth-child(2)').click()
      cy.get(':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Texas R&D')
      cy.get('.oxd-select-text').click({force: true})
      cy.get(':nth-child(227)').click({force: true})
      cy.get('.oxd-form-actions > .oxd-button--secondary').click({force: true})
    })
    it('success search Organization empty name', () => {
      cy.visit('https://opensource-demo.orangehrmlive.com/')
      cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Admin')
      cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
      cy.get('.oxd-button').click()
      cy.get('.oxd-brand-banner > img').should('be.visible')
      cy.get(':nth-child(1) > .oxd-main-menu-item > .oxd-text').click()
      cy.get(':nth-child(3) > .oxd-topbar-body-nav-tab-item').click()
      cy.get('.oxd-dropdown-menu > :nth-child(2)').click()
      cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Texas')
      cy.get('.oxd-select-text').click({force: true})
      cy.get(':nth-child(227)').click({force: true})
      cy.get('.oxd-form-actions > .oxd-button--secondary').click({force: true})
    })


    it('failed search Organization wrong country', () => {
        cy.visit('https://opensource-demo.orangehrmlive.com/')
        cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Admin')
        cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123')
        cy.get('.oxd-button').click()
        cy.get('.oxd-brand-banner > img').should('be.visible')
        cy.get(':nth-child(1) > .oxd-main-menu-item > .oxd-text').click()
        cy.get(':nth-child(3) > .oxd-topbar-body-nav-tab-item').click()
        cy.get('.oxd-dropdown-menu > :nth-child(2)').click()
        cy.get(':nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Texas R&D')
        cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Texas')
        cy.get('.oxd-select-text').click({force: true})
        cy.get(':nth-child(101) > span').click({force: true})
        cy.get('.oxd-form-actions > .oxd-button--secondary').click({force: true})
    })
})