import baseEditEmployee from "../../support/PageObject/employee/baseEditEmployee.cy.js"

describe('edit employee', () => {

    it('success edit employee', () => {
      const BaseEditEmployee = new baseEditEmployee()
    // login
      cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      cy.get(BaseEditEmployee.usernameInput).type('admin')
      cy.get(BaseEditEmployee.passwordInput).type('admin123')
      cy.get(BaseEditEmployee.loginButton).click()
      cy.get(BaseEditEmployee.dashboard).should('contain.text', 'Dashboard')

      cy.get(BaseEditEmployee.pimButton).click()
      cy.get(BaseEditEmployee.editKlik).click()
      cy.get(BaseEditEmployee.DlnInput).clear().type('308553')
      cy.get(BaseEditEmployee.LedInput).clear().type('2025-06-06').click()
      cy.get(BaseEditEmployee.SinnInput).clear().type('212259')
      cy.get(BaseEditEmployee.nationalityKlik).click()
      cy.get(BaseEditEmployee.indonesiaSelect).click()
      cy.get(BaseEditEmployee.msKlik).click()
      cy.get(BaseEditEmployee.singleSelect).click()
      cy.get(BaseEditEmployee.dobKlik).clear().type('2000-08-08').click({ force: true })
      cy.get(BaseEditEmployee.genderRadio).click({force: true})
      cy.get(BaseEditEmployee.saveButton1).click({force: true})
      cy.get(BaseEditEmployee.popupSuccess).should('contain.text', 'Successfully Updated')

      cy.get(BaseEditEmployee.btKlik).click()
      cy.get(BaseEditEmployee.oSelect).click()
      cy.get(BaseEditEmployee.saveButton2).click()
      cy.get(BaseEditEmployee.popupSuccess).should('contain.text', 'Successfully Updated')

      cy.get(BaseEditEmployee.showButtonAttacment).click()
      cy.get(BaseEditEmployee.selectFile).selectFile('cypress/fixtures/template.rtf', {force: true})
      cy.get(BaseEditEmployee.commentInput).type('blablabla')
      cy.get(BaseEditEmployee.saveButton3).click()

    })

    it('empty first name edit employee', () => {
      const BaseEditEmployee = new baseEditEmployee()
    // login
      cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      cy.get(BaseEditEmployee.usernameInput).type('admin')
      cy.get(BaseEditEmployee.passwordInput).type('admin123')
      cy.get(BaseEditEmployee.loginButton).click()
      cy.get(BaseEditEmployee.dashboard).should('contain.text', 'Dashboard')

      cy.get(BaseEditEmployee.pimButton).click()
      cy.get(BaseEditEmployee.editKlik).click()
      cy.get(BaseEditEmployee.firstNameInput).clear()
      cy.get(BaseEditEmployee.DlnInput).clear().type('308553')
      cy.get(BaseEditEmployee.LedInput).clear().type('2025-06-06').click()
      cy.get(BaseEditEmployee.SinnInput).clear().type('212259')
      cy.get(BaseEditEmployee.nationalityKlik).click()
      cy.get(BaseEditEmployee.indonesiaSelect).click()
      cy.get(BaseEditEmployee.msKlik).click()
      cy.get(BaseEditEmployee.singleSelect).click()
      cy.get(BaseEditEmployee.dobKlik).clear().type('2000-08-08').click({ force: true })
      cy.get(BaseEditEmployee.genderRadio).click({ force: true })
      cy.get(BaseEditEmployee.saveButton1).click({force: true})
      cy.get(BaseEditEmployee.requiredInfo).should('contain.text', 'Required')

      cy.get(BaseEditEmployee.btKlik).click()
      cy.get(BaseEditEmployee.oSelect).click()
      cy.get(BaseEditEmployee.saveButton2).click()
        
      cy.get(BaseEditEmployee.showButtonAttacment).click()
      cy.get(BaseEditEmployee.selectFile).selectFile('cypress/fixtures/template.rtf', {force: true})
      cy.get(BaseEditEmployee.commentInput).type('blablabla')
      cy.get(BaseEditEmployee.saveButton3).click()
    })

    it('empty last name edit employee', () => {
      const BaseEditEmployee = new baseEditEmployee()
    // login
      cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      cy.get(BaseEditEmployee.usernameInput).type('admin')
      cy.get(BaseEditEmployee.passwordInput).type('admin123')
      cy.get(BaseEditEmployee.loginButton).click()
      cy.get(BaseEditEmployee.dashboard).should('contain.text', 'Dashboard')

      cy.get(BaseEditEmployee.pimButton).click()
      cy.get(BaseEditEmployee.editKlik).click()
      cy.get(BaseEditEmployee.lastnameInput).clear()
      cy.get(BaseEditEmployee.DlnInput).clear().type('308553')
      cy.get(BaseEditEmployee.LedInput).clear().type('2025-06-06').click()
      cy.get(BaseEditEmployee.SinnInput).clear().type('212259')
      cy.get(BaseEditEmployee.nationalityKlik).click()
      cy.get(BaseEditEmployee.indonesiaSelect).click()
      cy.get(BaseEditEmployee.msKlik).click()
      cy.get(BaseEditEmployee.singleSelect).click()
      cy.get(BaseEditEmployee.dobKlik).clear().type('2000-08-08').click({ force: true })
      cy.get(BaseEditEmployee.genderRadio).click({ force: true })
      cy.get(BaseEditEmployee.saveButton1).click({force: true})
      cy.get(BaseEditEmployee.lastNameRequired).should('contain.text', 'Required')

      cy.get(BaseEditEmployee.btKlik).click()
      cy.get(BaseEditEmployee.oSelect).click()
      cy.get(BaseEditEmployee.saveButton2).click()

      cy.get(BaseEditEmployee.showButtonAttacment).click()
      cy.get(BaseEditEmployee.selectFile).selectFile('cypress/fixtures/template.rtf', {force: true})
      cy.get(BaseEditEmployee.commentInput).type('blablabla')
      cy.get(BaseEditEmployee.saveButton3).click()
    })

    it('employee id more than 10 edit employee', () => {
      const BaseEditEmployee = new baseEditEmployee()
    // login
      cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      cy.get(BaseEditEmployee.usernameInput).type('admin')
      cy.get(BaseEditEmployee.passwordInput).type('admin123')
      cy.get(BaseEditEmployee.loginButton).click()
      cy.get(BaseEditEmployee.dashboard).should('contain.text', 'Dashboard')

      cy.get(BaseEditEmployee.pimButton).click()
      cy.get(BaseEditEmployee.editKlik).click()
      cy.get(BaseEditEmployee.employeeIdInput).type(BaseEditEmployee.generateRandomEmployeeId2())
      cy.get(BaseEditEmployee.DlnInput).clear().type('308553')
      cy.get(BaseEditEmployee.LedInput).clear().type('2025-06-06').click()
      cy.get(BaseEditEmployee.SinnInput).clear().type('212259')
      cy.get(BaseEditEmployee.nationalityKlik).click()
      cy.get(BaseEditEmployee.indonesiaSelect).click()
      cy.get(BaseEditEmployee.msKlik).click()
      cy.get(BaseEditEmployee.singleSelect).click()
      cy.get(BaseEditEmployee.dobKlik).clear().type('2000-08-08').click({ force: true })
      cy.get(BaseEditEmployee.genderRadio).click({ force: true })
      cy.get(BaseEditEmployee.saveButton1).click({ force: true })
      cy.get(BaseEditEmployee.employeeIdMore).should('contain.text', 'Should not exceed 10 characters')

      cy.get(BaseEditEmployee.btKlik).click()
      cy.get(BaseEditEmployee.oSelect).click()
      cy.get(BaseEditEmployee.saveButton2).click({ force: true})

      cy.get(BaseEditEmployee.showButtonAttacment).click({ force: true })
      cy.get(BaseEditEmployee.selectFile).selectFile('cypress/fixtures/template.rtf', {force: true})
      cy.get(BaseEditEmployee.commentInput).type('blablabla')
      cy.get(BaseEditEmployee.saveButton3).click()
    })
    it('Drivers License Number more than 30 character edit employee', () => {
      const BaseEditEmployee = new baseEditEmployee()
    // login
      cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      cy.get(BaseEditEmployee.usernameInput).type('admin')
      cy.get(BaseEditEmployee.passwordInput).type('admin123')
      cy.get(BaseEditEmployee.loginButton).click()
      cy.get(BaseEditEmployee.dashboard).should('contain.text', 'Dashboard')

      cy.get(BaseEditEmployee.pimButton).click()
      cy.get(BaseEditEmployee.editKlik).click()
      cy.get(BaseEditEmployee.DlnInput).clear().type('308533333333333333333333333333333')
      cy.get(BaseEditEmployee.LedInput).clear().type('2026-06-06').click()
      cy.get(BaseEditEmployee.SinnInput).clear().type('212259')
      cy.get(BaseEditEmployee.nationalityKlik).click()
      cy.get(BaseEditEmployee.indonesiaSelect).click()
      cy.get(BaseEditEmployee.msKlik).click()
      cy.get(BaseEditEmployee.singleSelect).click()
      cy.get(BaseEditEmployee.dobKlik).clear().type('2000-08-08').click({ force: true })
      cy.get(BaseEditEmployee.genderRadio).click({ force: true })
      cy.get(BaseEditEmployee.saveButton1).click({ force: true })
      cy.get(BaseEditEmployee.dlnMore).should('contain.text', 'Should not exceed 30 characters')

      cy.get(BaseEditEmployee.btKlik).click()
      cy.get(BaseEditEmployee.oSelect).click()
      cy.get(BaseEditEmployee.saveButton2).click({ force: true })

      cy.get(BaseEditEmployee.showButtonAttacment).click({ force: true })
      cy.get(BaseEditEmployee.selectFile).selectFile('cypress/fixtures/template.rtf', {force: true})
      cy.get(BaseEditEmployee.commentInput).type('blablabla')
      cy.get(BaseEditEmployee.saveButton3).click()
    })
    it('SIN Number more than 30 character edit employee', () => {
      const BaseEditEmployee = new baseEditEmployee()
    // login
      cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
      cy.get(BaseEditEmployee.usernameInput).type('admin')
      cy.get(BaseEditEmployee.passwordInput).type('admin123')
      cy.get(BaseEditEmployee.loginButton).click()
      cy.get(BaseEditEmployee.dashboard).should('contain.text', 'Dashboard')

      cy.get(BaseEditEmployee.pimButton).click()
      cy.get(BaseEditEmployee.editKlik).click()
      cy.get(BaseEditEmployee.DlnInput).clear().type('3085333')
      cy.get(BaseEditEmployee.LedInput).clear().type('2026-06-06').click()
      cy.get(BaseEditEmployee.SinnInput).clear().type('212259999999999999999999999999999')
      cy.get(BaseEditEmployee.nationalityKlik).click()
      cy.get(BaseEditEmployee.indonesiaSelect).click()
      cy.get(BaseEditEmployee.msKlik).click()
      cy.get(BaseEditEmployee.singleSelect).click()
      cy.get(BaseEditEmployee.dobKlik).clear().type('2000-08-08').click({ force: true })
      cy.get(BaseEditEmployee.genderRadio).click({ force: true })
      cy.get(BaseEditEmployee.saveButton1).click({ force: true })
      cy.get(BaseEditEmployee.sinnMore).should('contain.text', 'Should not exceed 30 characters')

      cy.get(BaseEditEmployee.btKlik).click()
      cy.get(BaseEditEmployee.oSelect).click()
      cy.get(BaseEditEmployee.saveButton2).click({ force: true })

      cy.get(BaseEditEmployee.showButtonAttacment).click({ force: true })
      cy.get(BaseEditEmployee.selectFile).selectFile('cypress/fixtures/template.rtf', {force: true})
      cy.get(BaseEditEmployee.commentInput).type('blablabla')
      cy.get(BaseEditEmployee.saveButton3).click()
    })
  })
  
  